"""
LLMOps/Observability Logger

Provides comprehensive logging and tracing for agent operations,
tool calls, and workflow execution.
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, Optional
from pathlib import Path


class AgentLogger:
    """
    Logger for tracking agent operations in the Multi-Agent Grading System.
    
    Records:
    - Agent inputs and outputs
    - Tool calls with parameters and results
    - Processing time
    - State transitions
    - Errors and exceptions
    """
    
    def __init__(self, log_dir: str = "logs"):
        """
        Initialize the logger.
        
        Args:
            log_dir: Directory to store log files
        """
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(exist_ok=True)
        
        # Create session ID based on timestamp
        self.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.session_log_file = self.log_dir / f"grading_session_{self.session_id}.json"
        
        # Session log structure
        self.session_log = {
            'session_id': self.session_id,
            'start_time': datetime.now().isoformat(),
            'end_time': None,
            'agents_executed': [],
            'tools_called': [],
            'state_transitions': [],
            'errors': [],
            'summary': {}
        }
        
        print(f"📝 Logger initialized. Session ID: {self.session_id}")
        print(f"📁 Logs will be saved to: {self.session_log_file}")
    
    def log_agent_execution(
        self,
        agent_name: str,
        input_data: Dict[str, Any],
        output_data: Dict[str, Any],
        processing_time: float,
        status: str = "success"
    ):
        """
        Log an agent's execution details.
        
        Args:
            agent_name: Name of the agent
            input_data: Input provided to the agent
            output_data: Output generated by the agent
            processing_time: Time taken in seconds
            status: Execution status (success/failed)
        """
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'agent_name': agent_name,
            'status': status,
            'processing_time_seconds': processing_time,
            'input_summary': self._summarize_data(input_data),
            'output_summary': self._summarize_data(output_data)
        }
        
        self.session_log['agents_executed'].append(log_entry)
        self._save_log()
        
        print(f"✓ Agent '{agent_name}' executed in {processing_time:.2f}s [{status.upper()}]")
    
    def log_tool_call(
        self,
        tool_name: str,
        agent_name: str,
        parameters: Dict[str, Any],
        result: Any,
        execution_time: float,
        status: str = "success"
    ):
        """
        Log a tool call made by an agent.
        
        Args:
            tool_name: Name of the tool
            agent_name: Agent that called the tool
            parameters: Tool parameters
            result: Tool execution result
            execution_time: Time taken in seconds
            status: Execution status
        """
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'tool_name': tool_name,
            'called_by_agent': agent_name,
            'status': status,
            'execution_time_seconds': execution_time,
            'parameters': self._summarize_data(parameters, max_length=200),
            'result_summary': self._summarize_data(result, max_length=300)
        }
        
        self.session_log['tools_called'].append(log_entry)
        self._save_log()
        
        print(f"  🔧 Tool '{tool_name}' called by {agent_name} [{status.upper()}]")
    
    def log_state_transition(
        self,
        from_state: str,
        to_state: str,
        state_data: Optional[Dict[str, Any]] = None
    ):
        """
        Log a state transition in the workflow.
        
        Args:
            from_state: Previous state
            to_state: New state
            state_data: Current state data (optional)
        """
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'from_state': from_state,
            'to_state': to_state,
            'state_summary': self._summarize_data(state_data, max_length=500) if state_data else None
        }
        
        self.session_log['state_transitions'].append(log_entry)
        self._save_log()
    
    def log_error(
        self,
        error_type: str,
        error_message: str,
        context: Optional[Dict[str, Any]] = None
    ):
        """
        Log an error that occurred during execution.
        
        Args:
            error_type: Type of error
            error_message: Error description
            context: Additional context about the error
        """
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'error_type': error_type,
            'error_message': error_message,
            'context': self._summarize_data(context, max_length=500) if context else None
        }
        
        self.session_log['errors'].append(log_entry)
        self._save_log()
        
        print(f"❌ Error logged: {error_type} - {error_message}")
    
    def finalize_session(self, summary: Dict[str, Any]):
        """
        Finalize the logging session.
        
        Args:
            summary: Summary statistics for the session
        """
        self.session_log['end_time'] = datetime.now().isoformat()
        self.session_log['summary'] = summary
        
        self._save_log()
        
        print(f"\n{'='*60}")
        print(f"📊 Session Summary")
        print(f"{'='*60}")
        print(f"Session ID: {self.session_id}")
        print(f"Duration: {self._calculate_duration()}")
        print(f"Agents Executed: {len(self.session_log['agents_executed'])}")
        print(f"Tools Called: {len(self.session_log['tools_called'])}")
        print(f"Errors: {len(self.session_log['errors'])}")
        print(f"Log saved to: {self.session_log_file}")
        print(f"{'='*60}\n")
    
    def _summarize_data(self, data: Any, max_length: int = 200) -> str:
        """
        Create a summary of data for logging.
        
        Args:
            data: Data to summarize
            max_length: Maximum length of summary
            
        Returns:
            Summarized string representation
        """
        if data is None:
            return "None"
        
        try:
            if isinstance(data, dict):
                summary = json.dumps(data, indent=2, default=str)
            elif isinstance(data, str):
                summary = data
            else:
                summary = str(data)
            
            if len(summary) > max_length:
                return summary[:max_length] + "..."
            return summary
        except:
            return str(type(data))
    
    def _save_log(self):
        """Save the current log to file."""
        try:
            with open(self.session_log_file, 'w', encoding='utf-8') as f:
                json.dump(self.session_log, f, indent=2, default=str)
        except Exception as e:
            print(f"Warning: Could not save log file: {e}")
    
    def _calculate_duration(self) -> str:
        """Calculate session duration."""
        try:
            start = datetime.fromisoformat(self.session_log['start_time'])
            end = datetime.fromisoformat(self.session_log['end_time'])
            duration = end - start
            return str(duration)
        except:
            return "Unknown"
